// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ComplianceAndPeformanceSystem.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ComplianceAndPeformanceSystem.DAL.Configurations;

public partial class AspNetRoleConfiguration : IEntityTypeConfiguration<AspNetRole>
{
    public void Configure(EntityTypeBuilder<AspNetRole> entity)
    {
        entity.HasIndex(e => e.NormalizedName, "RoleNameIndex")
            .IsUnique()
            .HasFilter("([NormalizedName] IS NOT NULL)");

        entity.Property(e => e.Name).HasMaxLength(256);
        entity.Property(e => e.NormalizedName).HasMaxLength(256);

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<AspNetRole> entity);
}
