// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ComplianceAndPeformanceSystem.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ComplianceAndPeformanceSystem.DAL.Configurations;

public partial class AspNetUserConfiguration : IEntityTypeConfiguration<AspNetUser>
{
    public void Configure(EntityTypeBuilder<AspNetUser> entity)
    {
        entity.HasIndex(e => e.NormalizedEmail, "EmailIndex");

        entity.HasIndex(e => e.Email, "IX_AspNetUsers_Email")
            .IsUnique()
            .HasFilter("([Email] IS NOT NULL)");

        entity.HasIndex(e => e.ParentCompanyId, "IX_AspNetUsers_ParentCompanyId");

        entity.HasIndex(e => e.PhoneNumber, "IX_AspNetUsers_PhoneNumber")
            .IsUnique()
            .HasFilter("([PhoneNumber] IS NOT NULL)");

        entity.HasIndex(e => e.NormalizedUserName, "UserNameIndex")
            .IsUnique()
            .HasFilter("([NormalizedUserName] IS NOT NULL)");

        entity.Property(e => e.Email).HasMaxLength(256);
        entity.Property(e => e.IsActive).HasColumnName("isActive");
        entity.Property(e => e.NormalizedEmail).HasMaxLength(256);
        entity.Property(e => e.NormalizedUserName).HasMaxLength(256);
        entity.Property(e => e.UserName).HasMaxLength(256);

        entity.HasMany(d => d.Roles).WithMany(p => p.Users)
            .UsingEntity<Dictionary<string, object>>(
                "AspNetUserRole",
                r => r.HasOne<AspNetRole>().WithMany().HasForeignKey("RoleId"),
                l => l.HasOne<AspNetUser>().WithMany().HasForeignKey("UserId"),
                j =>
                {
                    j.HasKey("UserId", "RoleId");
                    j.ToTable("AspNetUserRoles");
                    j.HasIndex(new[] { "RoleId" }, "IX_AspNetUserRoles_RoleId");
                });

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<AspNetUser> entity);
}
