// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ComplianceAndPeformanceSystem.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ComplianceAndPeformanceSystem.DAL.Configurations;

public partial class LicenseConfiguration : IEntityTypeConfiguration<License>
{
    public void Configure(EntityTypeBuilder<License> entity)
    {
        entity.HasIndex(e => e.CompanyId, "IX_Licenses_CompanyId");

        entity.HasIndex(e => e.LicenseRequestId, "IX_Licenses_LicenseRequestId").IsUnique();

        entity.Property(e => e.CreatedBy).IsRequired();
        entity.Property(e => e.FinancialFees).HasColumnType("decimal(15, 2)");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<License> entity);
}
