// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ComplianceAndPeformanceSystem.Core.Entities;
using Microsoft.EntityFrameworkCore;

#nullable disable


namespace ComplianceAndPeformanceSystem.DAL;

public interface ISWAESContext
{
 
    public DbSet<AspNetRole> AspNetRoles { get; set; }

    public DbSet<AspNetUser> AspNetUsers { get; set; }

    public DbSet<License> Licenses { get; set; }

}
