// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ComplianceAndPeformanceSystem.Core.Entities;
using Microsoft.EntityFrameworkCore;

#nullable disable


namespace ComplianceAndPeformanceSystem.DAL;

public partial class SWAESContext : DbContext , ISWAESContext
{
    public SWAESContext(DbContextOptions<SWAESContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AspNetRole> AspNetRoles { get; set; }

    public virtual DbSet<AspNetUser> AspNetUsers { get; set; }

    public virtual DbSet<License> Licenses { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.AspNetRoleConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.AspNetUserConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.LicenseConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
