// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComplianceAndPeformanceSystem.Core.Entities;

public partial class License
{
    public int Id { get; set; }

    public DateTime IssueDate { get; set; }

    public DateOnly ExpiryDate { get; set; }

    public string CreatedBy { get; set; }

    public int CompanyId { get; set; }

    public int LicenseRequestId { get; set; }

    public DateOnly? CommercialRegisterEntryDate { get; set; }

    public string CommercialRegisterNumber { get; set; }

    public string CompanyName { get; set; }

    public string CompanyNameEnglish { get; set; }

    public int? IssueNumber { get; set; }

    public int? LicenseDuration { get; set; }

    public string LicenseNumber { get; set; }

    public string LicenseNumberEnglish { get; set; }

    public DateOnly LicenseStartDate { get; set; }

    public decimal? FinancialFees { get; set; }

    public int? LicenseSerial { get; set; }

    public bool IsManualLicenseNumber { get; set; }

    public int LicenseServiceId { get; set; }

    public string LicenseServiceName { get; set; }

    public string LicenseServiceNameAr { get; set; }

    public DateOnly? NafathDate { get; set; }
}